### ISSUE TITLE
Html saving

### ISSUE THREAD

**Issue by damioresegun** [wdecoster/nanoQC#6] opened 2018-04-09 14:09 UTC
Would it be possible to add a flag to save the report as images (like in previous versions?)

Also, I currently have an issue with the html being created at the moment. See screenshot below:
![image](https://user-images.githubusercontent.com/33520829/38502560-97ce7d1c-3c07-11e8-8b1e-193bb5c7f812.png)
 --- As you can see, it seems to only report the bottom trace plot. 

When I try to save the report, I get another plot saved. See below:
![image](https://user-images.githubusercontent.com/33520829/38502665-e7c5bf2e-3c07-11e8-9e62-d80edc63089d.png)

So yeah, I'm not sure if its my system or not. 

Thanks for having a look

**Comment by wdecoster** [comment] 2018-04-09 14:55
Hi, thanks for reporting this. That looks indeed unexpected. Can you check if the [example result](http://decoster.xyz/wouter/index.html) looks any better on your system?

**Comment by damioresegun** [comment] 2018-04-09 15:00
Yeah the example result opens up correctly and saves the plots into 5 individual files.

**Comment by wdecoster** [comment] 2018-04-09 15:20
Are you using NanoQC on a ton of data? Can you see if nanoQC works on your system on the fastq.gz from my test data in the [nanotest](https://github.com/wdecoster/nanotest) repository?

**Comment by damioresegun** [comment] 2018-04-09 17:36
No not on a ton of data. Literally just one fastq.gz file ~5000 reads.
Downloaded and tested it; same result. I'm guessing its my system then? No idea why though

**Comment by wdecoster** [comment] 2018-04-09 18:09
Well, where do we start. Can you share the html file, for example using dropbox or email? Which operating system are you using? Which browser? Can you try updating `bokeh` using 

    pip install bokeh -U

**Comment by damioresegun** [comment] 2018-04-10 11:39
I will email you with the html file produced as well as the info for my system

**Comment by wdecoster** [comment] 2018-04-10 12:04
I found in the source code of the html file you send me the following message:

"Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing"

Did updating bokeh help?

**Comment by iosefward** [comment] 2018-04-11 09:12
Currently working on this issue. Updating bokeh didn't help (despite python3 -m bokeh info saying it has the bokehjs path). Does look like a bokeh issue or a config issue somewhere though.

**Comment by wdecoster** [comment] 2018-05-30 10:07
Any progress on this? Still seeing this issue?

**Comment by iosefward** [comment] 2018-05-31 12:59
Still seeing the issue. I've had another look but still can't work out why it isn't seeing the BokehJS libraries. I've not got time at the moment to look at it in depth, but I think it's almost certainly an issue on our end rather than yours so feel free to close the issue.

Thanks for the help

**Comment by lukea-bioinf** [comment] 2018-06-14 13:52
Hi,
I also have the same issue and would appreciate any advice. iosefward did you manage to resolve the problem?
Cheers,
Luke

**Comment by wdecoster** [comment] 2018-06-14 14:10
I cannot reproduce this and am unfamiliar with the "internals" of bokeh, so I'm afraid I'm of limited help here.
Could you tell me how you installed bokeh, which python you use and which operating system?

Could you try updating bokeh with the installation instructions mentioned [here](https://anaconda.org/bokeh/bokeh)?

**Comment by beneblacklab** [comment] 2019-05-11 16:24
I am also having this issue where I have BokehJS installed, but I have an error in the nanoQC.html that says "Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing".

I am running nanoQC on one 563 kb fastq.gz read, and my output is here: https://eichlerlab.gs.washington.edu/help/glogsdon/public_html/CHM13/tiling_across_centromere/Tile1/nanoQC/nanoQC.html

I also noticed that the plots on the bottom both state "position in read from start", and I think the one on the bottom right should say "position in read from end". Also, what are the units here? bp? Can this be modified to be even greater (say 100 kbp)?

**Comment by glogsdon1** [comment] 2019-05-11 16:25
I am also having this issue where I have Bokeh installed, but I have an error in the nanoQC.html that says "Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing".

I am running nanoQC on one 563 kb fastq.gz read, and my output is here: https://eichlerlab.gs.washington.edu/help/glogsdon/public_html/CHM13/tiling_across_centromere/Tile1/nanoQC/nanoQC.html

I also noticed that the plots on the bottom both state "position in read from start", and I think the one on the bottom right should say "position in read from end". Also, what are the units here? bp? Can this be modified to be even greater (say 100 kbp)?

**Comment by glogsdon1** [comment] 2019-05-11 16:32
I am also having this issue where I have Bokeh installed, but I have an error in the nanoQC.html that says "Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing".

I am running nanoQC on one 563 kb fastq.gz read, and my output is here: https://eichlerlab.gs.washington.edu/help/glogsdon/public_html/shared/nanoQC.html

I also noticed that the plots on the bottom both state "position in read from start", and I think the one on the bottom right should say "position in read from end". Also, what are the units here? bp? Can this be modified to be even greater (say 100 kbp)?

**Comment by wdecoster** [comment] 2019-05-13 13:48
So you cannot see the output below, which I get from your link?

![image](https://user-images.githubusercontent.com/11660522/57626304-e8556c00-7595-11e9-9bd4-abbbca9a579c.png)

You are right about "position in read from start" should be "position in read from end" in the bottom right, I'll correct that in a couple of minutes. It seems you are trying to plot a single very long read? That's not the use-case for which I wrote this tool, but it should work in principle. Note that there is a `-l/--minlen` argument, with default value 200 (bp), which also controls the length of the plots (length/2). Setting this to a higher value would increase the area in the plot. I agree that this is poorly documented.

**Comment by splaisan** [comment] 2019-05-13 13:53
Hi Wout, please look at the bottom right plot having start instead of end in its x axis name

**Comment by wdecoster** [comment] 2019-05-13 13:55
Yes, I have fixed that in https://github.com/wdecoster/nanoQC/commit/373167ab4e61861d4093fe6b4450a243aa71cbe6. The fix is now on PyPI, v0.9.1.

**Comment by glogsdon1** [comment] 2019-05-13 22:30
Hi Wout,

Yes, I can see the output (I should have been more clear that I could see this in my earlier comment). Thanks for fixing the x-axis title on the bottom right graph and letting me know about the `-l/--minlen` argument. I agree that it could be really useful if you add a list of arguments to the README or --help, which could improve usability.

Thanks!
Glennis

**Closed as completed** 2022-01-21 10:31 UTC
